# Title and tagline used in title tag together: `Title | Tagline`
title: Cyberbellum
tagline: A digital garden
description: >- # longer description for description meta tag
    A collection of notes, resources, thoughts, and lists. Nothing is finished, all is in flux.
url: https://cyberbellum.netlify.app
#logo:
author: Kyanne Rose
social:
    name: Kyanne Rose
    links:
        - https://keybase.io/kyrose
        - https://github.com/kyrose
        - https://twitter.com/kyr0se
        - https://openlibrary.org/people/kyrose2842
        - https://www.linkedin.com/in/kyannerose

twitter:
    username: kyr0se
    card: summary


include: ['_pages']
exclude: ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
